version: '3'
services:
  web:
    image: "goride_app:1"
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/app.goride
  db:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_USER: publiser
      POSTGRES_PASSWORD: publisher
      POSTGRES_DB: order
  redis:
    image: "redis:alpine"
