version: 1
jobs:
  build:
    working_directory: /go/src/app.goride/
    docker:
      - image: circleci/golang:1.8
      - image: circleci/postgres:9.4.12-alpine
        environment:
          POSTGRES_USER: joseph
          POSTGRES_PASSWORD: joseph
          POSTGRES_DB: order
    environment:
      TEST_RESULTS: /tmp/test-results
      HEROKU: false
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run: go get -u -v -t github.com/Masterminds/glide
      - run: glide install -v
      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1
      - run:
          name: Run migration
          command: |
            go run database_1.go